window.ITEM_BALANCE_CONFIG = {
    items: [
        // --- Weapons ---
        { id: 'cheater-sword', tier: 0, name: 'Cheater sword', type: 'WEAPON', power: 9999, slots: 80, baseShopPrice: 50000, baseSellPrice: 25000, enchantments: 'ALL', hiddenName: 'Mysterious blade', burnable: false },
        { id: 'rusted-sword', tier: 1, name: 'Rusted sword', type: 'WEAPON', power: 3, slots: 7, baseShopPrice: 40, baseSellPrice: 20, hiddenName: 'Mysterious blade', burnable: false },
        { id: 'bronze-sword', tier: 2, name: 'Bronze sword', type: 'WEAPON', power: 4, slots: 6, baseShopPrice: 65, baseSellPrice: 32, hiddenName: 'Mysterious blade', burnable: false },
        { id: 'iron-sword', tier: 3, name: 'Iron sword', type: 'WEAPON', power: 5, slots: 5, baseShopPrice: 95, baseSellPrice: 47, hiddenName: 'Mysterious blade', burnable: false },
        { id: 'fancy-sword', tier: 4, name: 'Fancy sword', type: 'WEAPON', power: 8, slots: 4, baseShopPrice: 145, baseSellPrice: 72, setId: 'warrior', hiddenName: 'Mysterious blade', burnable: false },
        { id: 'pickaxe', tier: 4, name: 'Pickaxe', type: 'WEAPON', power: 1, slots: 0, breaksWalls: true, spawnImprovementMin: 5, spawnImprovementMax: 10, baseShopPrice: 170, baseSellPrice: 85, hiddenName: 'Mysterious blade', burnable: false },
        // --- Armor ---
        { id: 'cheater-armor', tier: 0, name: 'Cheater armor', type: 'ARMOR', armor: 9999, slots: 80, baseShopPrice: 50000, baseSellPrice: 25000, enchantments: 'ALL', hiddenName: 'Unknown armor', burnable: false },
        { id: 'rags', tier: 1, name: 'Rags', type: 'ARMOR', armor: 3, slots: 7, baseShopPrice: 35, baseSellPrice: 17, hiddenName: 'Unknown armor', burnable: true },
        { id: 'leather-armor', tier: 2, name: 'Leather armor', type: 'ARMOR', armor: 4, slots: 6, baseShopPrice: 60, baseSellPrice: 30, hiddenName: 'Unknown armor', burnable: true },
        { id: 'chainmail-armor', tier: 3, name: 'Chainmail armor', type: 'ARMOR', armor: 6, slots: 5, baseShopPrice: 95, baseSellPrice: 47, hiddenName: 'Unknown armor', burnable: false },
        { id: 'plate-armor', tier: 4, name: 'Plate armor', type: 'ARMOR', armor: 8, slots: 4, baseShopPrice: 150, baseSellPrice: 75, setId: 'warrior', hiddenName: 'Unknown armor', burnable: false },
        // --- Shields ---
        { id: 'cheater-shield', tier: 0, name: 'Cheater shield', type: 'SHIELD', armor: 9999, slots: 80, baseShopPrice: 50000, baseSellPrice: 25000, enchantments: 'ALL', hiddenName: 'Mysterious shield', burnable: false },
        { id: 'rotten-shield', tier: 1, name: 'Rotten shield', type: 'SHIELD', armor: 3, slots: 7, baseShopPrice: 30, baseSellPrice: 15, hiddenName: 'Mysterious shield', burnable: true },
        { id: 'wooden-shield', tier: 2, name: 'Wooden shield', type: 'SHIELD', armor: 4, slots: 6, baseShopPrice: 55, baseSellPrice: 27, hiddenName: 'Mysterious shield', burnable: true },
        { id: 'kite-shield', tier: 3, name: 'Kite shield', type: 'SHIELD', armor: 6, slots: 5, baseShopPrice: 90, baseSellPrice: 45, hiddenName: 'Mysterious shield', burnable: false },
        { id: 'tower-shield', tier: 4, name: 'Tower shield', type: 'SHIELD', armor: 8, slots: 4, baseShopPrice: 145, baseSellPrice: 72, setId: 'warrior', hiddenName: 'Mysterious shield', burnable: false },
        // --- Accessories ---
        { id: 'cheater-accessory', tier: 0, name: 'Cheater accessory', type: 'ACCESSORY', power: 9999, armor: 9999, slots: 80, baseShopPrice: 50000, baseSellPrice: 25000, enchantments: 'ALL', hiddenName: 'Unknown ring', burnable: false },
        { id: 'copper-ring', tier: 1, name: 'Copper ring', type: 'ACCESSORY', power: 5, slots: 3, baseShopPrice: 70, baseSellPrice: 35, hiddenName: 'Unknown ring', burnable: false },
        { id: 'copper-bracelet', tier: 1, name: 'Copper bracelet', type: 'ACCESSORY', armor: 5, slots: 3, baseShopPrice: 70, baseSellPrice: 35, hiddenName: 'Unknown ring', burnable: false },
        { id: 'bronze-ring', tier: 2, name: 'Bronze ring', type: 'ACCESSORY', power: 10, slots: 3, baseShopPrice: 110, baseSellPrice: 55, hiddenName: 'Unknown ring', burnable: false },
        { id: 'bronze-bracelet', tier: 2, name: 'Bronze bracelet', type: 'ACCESSORY', armor: 10, slots: 3, baseShopPrice: 110, baseSellPrice: 55, hiddenName: 'Unknown ring', burnable: false },
        { id: 'waterwalk-ring', tier: 3, name: 'Waterwalk ring', type: 'ACCESSORY', enchantments: ['waterwalk'], slots: 3, baseShopPrice: 160, baseSellPrice: 80, hiddenName: 'Unknown ring', burnable: false },
        { id: 'lavawalk-bracelet', tier: 3, name: 'Lavawalk bracelet', type: 'ACCESSORY', enchantments: ['lavawalk'], slots: 3, baseShopPrice: 160, baseSellPrice: 80, hiddenName: 'Unknown ring', burnable: false },
        { id: 'flying-amulet', tier: 3, name: 'Flying amulet', type: 'ACCESSORY', enchantments: ['fly'], slots: 3, baseShopPrice: 190, baseSellPrice: 95, hiddenName: 'Unknown ring', burnable: false },
        { id: 'scholar-charm', tier: 4, name: 'Scholar charm', type: 'ACCESSORY', enchantments: ['scholar'], slots: 3, baseShopPrice: 180, baseSellPrice: 90, hiddenName: 'Unknown ring', burnable: false },
        { id: 'sustenance-charm', tier: 4, name: 'Sustenance charm', type: 'ACCESSORY', enchantments: ['sustenance'], slots: 3, baseShopPrice: 180, baseSellPrice: 90, hiddenName: 'Unknown ring', burnable: false },
        { id: 'vitality-charm', tier: 4, name: 'Vitality charm', type: 'ACCESSORY', enchantments: ['vitality'], slots: 3, baseShopPrice: 180, baseSellPrice: 90, hiddenName: 'Unknown ring', burnable: false },
        { id: 'hunter-lens', tier: 4, name: 'Hunter lens', type: 'ACCESSORY', enchantments: ['enemySight'], slots: 3, baseShopPrice: 180, baseSellPrice: 90, hiddenName: 'Unknown ring', burnable: false },
        { id: 'treasure-lens', tier: 4, name: 'Treasure lens', type: 'ACCESSORY', enchantments: ['itemSight'], slots: 3, baseShopPrice: 180, baseSellPrice: 90, hiddenName: 'Unknown ring', burnable: false },
        { id: 'appraiser-monocle', tier: 4, name: 'Appraiser monocle', type: 'ACCESSORY', enchantments: ['appraiser'], slots: 3, baseShopPrice: 180, baseSellPrice: 90, hiddenName: 'Unknown ring', burnable: false },
        { id: 'mining-hardhat', tier: 4, name: 'Mining hardhat', type: 'ACCESSORY', enchantments: ['miner'], slots: 3, baseShopPrice: 190, baseSellPrice: 95, hiddenName: 'Unknown ring', burnable: false },
        // --- Healing Items ---
        { id: 'old-bandage', tier: 1, name: 'Old bandage', type: 'CONSUMABLE', health: 10, baseShopPrice: 12, baseSellPrice: 6, hiddenName: 'Unknown consumable', burnable: true, requiresIdentification: false },
        { id: 'diluted-potion', tier: 2, name: 'Diluted potion', type: 'CONSUMABLE', health: 20, baseShopPrice: 24, baseSellPrice: 12, hiddenName: 'Unknown consumable', burnable: true, requiresIdentification: false },
        { id: 'healing-potion', tier: 3, name: 'Healing potion', type: 'CONSUMABLE', health: 40, baseShopPrice: 50, baseSellPrice: 25, hiddenName: 'Unknown consumable', burnable: true, requiresIdentification: false },
        { id: 'greater-healing-potion', tier: 4, name: 'Greater healing potion', type: 'CONSUMABLE', health: 80, baseShopPrice: 120, baseSellPrice: 60, hiddenName: 'Unknown consumable', burnable: true, requiresIdentification: false },
        // --- Food Items ---
        { id: 'bitter-seeds', tier: 1, name: 'Bitter seeds', type: 'CONSUMABLE', hunger: 25, baseShopPrice: 6, baseSellPrice: 3, hiddenName: 'Unknown consumable', burnable: true, requiresIdentification: false },
        { id: 'apple', tier: 2, name: 'Apple', type: 'CONSUMABLE', hunger: 50, baseShopPrice: 12, baseSellPrice: 6, hiddenName: 'Unknown consumable', burnable: true, requiresIdentification: false },
        { id: 'bread', tier: 3, name: 'Bread', type: 'CONSUMABLE', hunger: 100, baseShopPrice: 24, baseSellPrice: 12, hiddenName: 'Unknown consumable', burnable: true, requiresIdentification: false },
        { id: 'stew', tier: 4, name: 'Stew', type: 'CONSUMABLE', hunger: 200, baseShopPrice: 60, baseSellPrice: 30, hiddenName: 'Unknown consumable', burnable: true, requiresIdentification: false },

        // --- Throwables ---
        { id: 'pebble', tier: 1, name: 'Pebble', type: 'THROWABLE', power: 5, baseShopPrice: 8, baseSellPrice: 4, hiddenName: 'Mysterious throwable', burnable: true, requiresIdentification: false },
        { id: 'sharp-rock', tier: 2, name: 'Sharp rock', type: 'THROWABLE', power: 10, baseShopPrice: 18, baseSellPrice: 9, hiddenName: 'Mysterious throwable', burnable: true, requiresIdentification: false },
        { id: 'pushback-crystal', tier: 2, name: 'Pushback crystal', type: 'THROWABLE', power: 5, throwEffect: 'pushback', baseShopPrice: 26, baseSellPrice: 13, hiddenName: 'Mysterious throwable', burnable: true, requiresIdentification: false },
        { id: 'ninja-star', tier: 3, name: 'Ninja star', type: 'THROWABLE', power: 15, baseShopPrice: 34, baseSellPrice: 17, hiddenName: 'Mysterious throwable', burnable: true, requiresIdentification: false },
        { id: 'blink-crystal', tier: 3, name: 'Blink crystal', type: 'THROWABLE', throwEffect: 'blink', breakOnWall: true, baseShopPrice: 52, baseSellPrice: 26, hiddenName: 'Mysterious throwable', burnable: true, requiresIdentification: false },
        { id: 'javelin', tier: 4, name: 'Javelin', type: 'THROWABLE', power: 20, baseShopPrice: 60, baseSellPrice: 30, hiddenName: 'Mysterious throwable', burnable: true, requiresIdentification: false },
        { id: 'switch-crystal', tier: 4, name: 'Switch crystal', type: 'THROWABLE', throwEffect: 'switch', baseShopPrice: 80, baseSellPrice: 40, hiddenName: 'Mysterious throwable', burnable: true, requiresIdentification: false },

        // --- Status Consumables ---
        { id: 'poison-brew', tier: 1, name: 'Poison brew', type: 'CONSUMABLE', condition: 'POISONED', baseShopPrice: 20, baseSellPrice: 10, hiddenName: 'Unknown consumable', burnable: true, requiresIdentification: false },
        { id: 'sleeping-draught', tier: 1, name: 'Sleeping draught', type: 'CONSUMABLE', condition: 'SLEEP', baseShopPrice: 22, baseSellPrice: 11, hiddenName: 'Unknown consumable', burnable: true, requiresIdentification: false },
        { id: 'fright-powder', tier: 1, name: 'Fright powder', type: 'CONSUMABLE', condition: 'FRIGHTENED', baseShopPrice: 22, baseSellPrice: 11, hiddenName: 'Unknown consumable', burnable: true, requiresIdentification: false },
        { id: 'spoiled-milk', tier: 1, name: 'Spoiled milk', type: 'CONSUMABLE', condition: 'HUNGRY', baseShopPrice: 16, baseSellPrice: 8, hiddenName: 'Unknown consumable', burnable: true, requiresIdentification: false },
        { id: 'viscous-slime-tincture', tier: 2, name: 'Viscous slime tincture', type: 'CONSUMABLE', condition: 'SLOW', baseShopPrice: 34, baseSellPrice: 17, hiddenName: 'Unknown consumable', burnable: true, requiresIdentification: false, dropOnlyEnemyTypes: ['SLIME'] },
        { id: 'haste-potion', tier: 2, name: 'Haste potion', type: 'CONSUMABLE', condition: 'HASTE', baseShopPrice: 40, baseSellPrice: 20, hiddenName: 'Unknown consumable', burnable: true, requiresIdentification: false },
        { id: 'methanol-jug', tier: 3, name: 'Methanol jug', type: 'CONSUMABLE', condition: 'BLIND', baseShopPrice: 55, baseSellPrice: 27, hiddenName: 'Unknown consumable', burnable: true, requiresIdentification: false },
        { id: 'invisibility-salve', tier: 3, name: 'Invisibility salve', type: 'CONSUMABLE', condition: 'INVISIBLE', baseShopPrice: 65, baseSellPrice: 32, hiddenName: 'Unknown consumable', burnable: true, requiresIdentification: false },
        { id: 'shard-of-madness', tier: 3, name: 'Shard of madness', type: 'CONSUMABLE', condition: 'BERSERK', baseShopPrice: 65, baseSellPrice: 32, hiddenName: 'Unknown consumable', burnable: true, requiresIdentification: false },
        { id: 'petrification-salts', tier: 4, name: 'Petrification salts', type: 'CONSUMABLE', condition: 'BOUND', baseShopPrice: 90, baseSellPrice: 45, hiddenName: 'Unknown consumable', burnable: true, requiresIdentification: false },
        { id: 'holy-water', tier: 4, name: 'Holy water', type: 'CONSUMABLE', condition: 'BLESSED', baseShopPrice: 95, baseSellPrice: 47, hiddenName: 'Unknown consumable', burnable: true, requiresIdentification: false },
        { id: 'invincibility-elixir', tier: 4, name: 'Invincibility elixir', type: 'CONSUMABLE', condition: 'INVINCIBILITY', baseShopPrice: 150, baseSellPrice: 75, hiddenName: 'Unknown consumable', burnable: true, requiresIdentification: false },
        { id: 'garlic-chicken-pizza', tier: 4, name: 'Garlic chicken pizza', type: 'CONSUMABLE', condition: 'SATIATED', baseShopPrice: 100, baseSellPrice: 50, hiddenName: 'Unknown consumable', burnable: true, requiresIdentification: false },

        // --- Scrolls ---
        { id: 'trap-eraser-scroll', tier: 1, name: 'Trap eraser scroll', type: 'CONSUMABLE', scrollEffect: 'erase-traps', baseShopPrice: 45, baseSellPrice: 22, hiddenName: 'Unknown consumable', burnable: true, requiresIdentification: false },
        { id: 'mapping-scroll', tier: 1, name: 'Mapping scroll', type: 'CONSUMABLE', scrollEffect: 'map-floor', baseShopPrice: 45, baseSellPrice: 22, hiddenName: 'Unknown consumable', burnable: true, requiresIdentification: false },
        { id: 'identifying-scroll', tier: 2, name: 'Identifying scroll', type: 'CONSUMABLE', scrollEffect: 'identify-item', targetItemTypes: ['WEAPON','ARMOR','SHIELD','ACCESSORY','CONSUMABLE','THROWABLE'], baseShopPrice: 70, baseSellPrice: 35, hiddenName: 'Unknown consumable', burnable: true, requiresIdentification: false },
        { id: 'gilding-scroll', tier: 2, name: 'Gilding scroll', type: 'CONSUMABLE', scrollEffect: 'add-gilded', targetItemTypes: ['WEAPON','ARMOR','SHIELD','ACCESSORY'], baseShopPrice: 85, baseSellPrice: 42, hiddenName: 'Unknown consumable', burnable: true, requiresIdentification: false },
        { id: 'purifying-scroll', tier: 3, name: 'Purifying scroll', type: 'CONSUMABLE', scrollEffect: 'purify-item', targetItemTypes: ['WEAPON','ARMOR','SHIELD','ACCESSORY','CONSUMABLE','THROWABLE'], baseShopPrice: 95, baseSellPrice: 47, hiddenName: 'Unknown consumable', burnable: true, requiresIdentification: false },
        { id: 'warp-scroll', tier: 3, name: 'Warp scroll', type: 'CONSUMABLE', scrollEffect: 'warp-player', baseShopPrice: 110, baseSellPrice: 55, hiddenName: 'Unknown consumable', burnable: true, requiresIdentification: false },
        { id: 'earthly-power-scroll', tier: 4, name: 'Earthly power scroll', type: 'CONSUMABLE', improvesItemTypes: ['ARMOR','SHIELD'], baseShopPrice: 140, baseSellPrice: 70, hiddenName: 'Unknown consumable', burnable: true, requiresIdentification: false },
        { id: 'heavenly-power-scroll', tier: 4, name: 'Heavenly power scroll', type: 'CONSUMABLE', improvesItemTypes: ['WEAPON','ACCESSORY'], baseShopPrice: 140, baseSellPrice: 70, hiddenName: 'Unknown consumable', burnable: true, requiresIdentification: false },
        { id: 'slot-adding-scroll', tier: 4, name: 'Slot adding scroll', type: 'CONSUMABLE', scrollEffect: 'add-slot', targetItemTypes: ['WEAPON','ARMOR','SHIELD','ACCESSORY'], baseShopPrice: 165, baseSellPrice: 82, hiddenName: 'Unknown consumable', burnable: true, requiresIdentification: false },

        // --- Staves ---
        { id: 'teleport-staff', tier: 1, name: 'Teleport staff', type: 'STAFF', charges: 3, maxCharges: 3, staffEffect: 'blink', baseShopPrice: 90, baseSellPrice: 45, hiddenName: 'Unknown staff', requiresIdentification: true, breakOnThrow: true },
        { id: 'switch-staff', tier: 1, name: 'Switch staff', type: 'STAFF', charges: 3, maxCharges: 3, staffEffect: 'switch', baseShopPrice: 90, baseSellPrice: 45, hiddenName: 'Unknown staff', requiresIdentification: true, breakOnThrow: true },

        // --- Pots ---
        { id: 'basic-pot', tier: 1, name: 'Basic pot', type: 'POT', potType: 'basic', minCapacity: 3, maxCapacity: 5, baseShopPrice: 20, baseSellPrice: 10, hiddenName: 'Unknown pot' },
        { id: 'randomizer-pot', tier: 1, name: 'Randomizer pot', type: 'POT', potType: 'randomizer', minCapacity: 2, maxCapacity: 5, baseShopPrice: 42, baseSellPrice: 21, hiddenName: 'Unknown pot' },
        { id: 'money-pot', tier: 1, name: 'Money pot', type: 'POT', potType: 'money', minCapacity: 2, maxCapacity: 5, baseShopPrice: 36, baseSellPrice: 18, hiddenName: 'Unknown pot' },
        { id: 'food-pot', tier: 1, name: 'Food pot', type: 'POT', potType: 'food', minCapacity: 2, maxCapacity: 5, baseShopPrice: 28, baseSellPrice: 14, hiddenName: 'Unknown pot' },
        { id: 'banking-pot', tier: 1, name: 'Banking pot', type: 'POT', potType: 'banking', minCapacity: 2, maxCapacity: 3, baseShopPrice: 42, baseSellPrice: 21, hiddenName: 'Unknown pot' }
    ],
    enchantmentTuning: {
        hungerPower: { hungerPowerMultiplier: 1.3 },
        bloodyPower: { bloodyPowerMultiplier: 1.3 },
        inflictPoison: { inflictChance: 0.2 },
        inflictSlow: { inflictChance: 0.2 },
        inflictSleep: { inflictChance: 0.2 },
        inflictFrightened: { inflictChance: 0.2 },
        inflictBlind: { inflictChance: 0.2 },
        inflictBound: { inflictChance: 0.2 },
        inflictBerserk: { inflictChance: 0.2 },
        preventPoison: { preventionChance: 0.75 },
        preventSlow: { preventionChance: 0.75 },
        preventSleep: { preventionChance: 0.75 },
        preventFrightened: { preventionChance: 0.75 },
        preventBlind: { preventionChance: 0.75 },
        preventBound: { preventionChance: 0.75 },
        preventBerserk: { preventionChance: 0.75 },
        slayer: { damageMultiplier: 1.1 },
        beastSlayer: { damageMultiplierByEnemyType: { BEAST: 1.1 } },
        slimeSlayer: { damageMultiplierByEnemyType: { SLIME: 1.1 } },
        aquaticSlayer: { damageMultiplierByEnemyType: { AQUATIC: 1.1 } },
        floatingSlayer: { damageMultiplierByEnemyType: { FLOATING: 1.1 } },
        ghostSlayer: { damageMultiplierByEnemyType: { GHOST: 1.1 } },
        vandalSlayer: { damageMultiplierByEnemyType: { VANDAL: 1.1 } },
        fuserSlayer: { damageMultiplierByEnemyType: { FUSER: 1.1 } },
        pariahSlayer: { damageMultiplierByEnemyType: { PARIAH: 1.1 } },
        crafterSlayer: { damageMultiplierByEnemyType: { CRAFTER: 1.1 } },
        defender: { shieldMultiplier: 1.1 },
        beastDefender: { shieldMultiplierByEnemyType: { BEAST: 1.1 } },
        slimeDefender: { shieldMultiplierByEnemyType: { SLIME: 1.1 } },
        aquaticDefender: { shieldMultiplierByEnemyType: { AQUATIC: 1.1 } },
        floatingDefender: { shieldMultiplierByEnemyType: { FLOATING: 1.1 } },
        ghostDefender: { shieldMultiplierByEnemyType: { GHOST: 1.1 } },
        vandalDefender: { shieldMultiplierByEnemyType: { VANDAL: 1.1 } },
        fuserDefender: { shieldMultiplierByEnemyType: { FUSER: 1.1 } },
        pariahDefender: { shieldMultiplierByEnemyType: { PARIAH: 1.1 } },
        crafterDefender: { shieldMultiplierByEnemyType: { CRAFTER: 1.1 } },
        scholar: { expGainMultiplier: 1.25 },
        sustenance: { passiveHungerLossIntervalMultiplier: 2 },
        vitality: { passiveHealingBonus: 1 },
        counter: { counterReflectRatio: 0.1 }
    },
    defaultShopPriceByCategory: {
        healing: [0, 12, 24, 50, 120],
        food: [0, 6, 12, 24, 60],
        throwable: [0, 8, 20, 40, 70],
        weapon: [0, 40, 65, 95, 145],
        armor: [0, 35, 60, 95, 150],
        shield: [0, 30, 55, 90, 145],
        accessory: [0, 70, 110, 170, 185],
        statusConsumable: [0, 20, 36, 60, 95],
        scroll: [0, 45, 75, 100, 145],
        pot: [0, 20, 28, 36, 42]
    },
    itemSpawnPoolByTier: {
        1: [
            { category: 'staff', tier: 1, weight: 1 },
            { category: 'money', tier: 1, weight: 4 },
            { category: 'healing', tier: 1, weight: 4 },
            { category: 'food', tier: 1, weight: 4 },
            { category: 'pot', tier: 1, weight: 1 },
            { category: 'statusConsumable', tier: 1, weight: 2 },
            { category: 'scroll', tier: 1, weight: 1 },
            { category: 'throwable', tier: 1, weight: 3 },
            { category: 'weapon', tier: 1, weight: 2 },
            { category: 'armor', tier: 1, weight: 2 },
            { category: 'shield', tier: 1, weight: 2 },
            { category: 'accessory', tier: 1, weight: 1 }
        ],
        2: [
            { category: 'money', tier: 2, weight: 4 },
            { category: 'healing', tier: 2, weight: 4 },
            { category: 'food', tier: 2, weight: 4 },
            { category: 'pot', tier: 1, weight: 1 },
            { category: 'statusConsumable', tier: 2, weight: 2 },
            { category: 'scroll', tier: 2, weight: 1 },
            { category: 'throwable', tier: 2, weight: 3 },
            { category: 'weapon', tier: 2, weight: 2 },
            { category: 'armor', tier: 2, weight: 2 },
            { category: 'shield', tier: 2, weight: 2 },
            { category: 'accessory', tier: 2, weight: 1 }
        ],
        3: [
            { category: 'money', tier: 3, weight: 4 },
            { category: 'healing', tier: 3, weight: 4 },
            { category: 'food', tier: 3, weight: 4 },
            { category: 'pot', tier: 1, weight: 1 },
            { category: 'statusConsumable', tier: 3, weight: 2 },
            { category: 'scroll', tier: 3, weight: 1 },
            { category: 'throwable', tier: 3, weight: 3 },
            { category: 'weapon', tier: 3, weight: 2 },
            { category: 'armor', tier: 3, weight: 2 },
            { category: 'shield', tier: 3, weight: 2 },
            { category: 'accessory', tier: 3, weight: 1 }
        ],
        4: [
            { category: 'money', tier: 4, weight: 4 },
            { category: 'healing', tier: 4, weight: 4 },
            { category: 'food', tier: 4, weight: 4 },
            { category: 'pot', tier: 1, weight: 1 },
            { category: 'statusConsumable', tier: 4, weight: 2 },
            { category: 'scroll', tier: 4, weight: 1 },
            { category: 'throwable', tier: 4, weight: 3 },
            { category: 'weapon', tier: 4, weight: 2 },
            { category: 'armor', tier: 4, weight: 2 },
            { category: 'shield', tier: 4, weight: 2 },
            { category: 'accessory', tier: 4, weight: 1 }
        ]
    }
};

